# Generated by Django 5.2 on 2025-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tickets_bought",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
