# Generated by Django 5.2 on 2025-04-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_place",
            new_name="place",
        ),
        migrations.RemoveField(
            model_name="event",
            name="cancel_date",
        ),
        migrations.AddField(
            model_name="eventplace",
            name="days_before_cancel",
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
