# Generated by Django 5.2 on 2025-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_rename_event_place_event_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplace",
            name="title",
            field=models.CharField(
                default="Event place title", max_length=200, unique=True
            ),
            preserve_default=False,
        ),
    ]
