# Generated by Django 5.2 on 2025-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventplace_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="ticket_id",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
