# Generated by Django 5.2 on 2025-05-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_ticket_ticket_id_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('declined', 'declined'), ('cancelled', 'cancelled'), ('closed', 'closed')], default='submitted', max_length=10),
        ),
    ]
