# Generated by Django 5.2 on 2025-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventplace",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
