# Generated by Django 5.2 on 2025-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_eventplace_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.CharField(default="http://google.com"),
            preserve_default=False,
        ),
    ]
