# Generated by Django 5.2 on 2025-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplace',
            name='location_url',
            field=models.CharField(default='https://maps.app.goo.gl/E4mhMmnFFaCFrVGx6'),
            preserve_default=False,
        ),
    ]
