# Generated by Django 5.2 on 2025-07-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_eventplace_location_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="pending_is_redeemed",
            field=models.BooleanField(default=False),
        ),
    ]
