# Generated by Django 5.2 on 2025-10-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_eventplace_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplace",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "submitted"),
                    ("approved", "approved"),
                    ("declined", "declined"),
                ],
                default="submitted",
                max_length=10,
            ),
        ),
    ]
