# Generated by Django 5.2 on 2025-10-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_eventplace_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplace",
            name="geometry",
            field=models.JSONField(
                default=dict,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="eventplace",
            name="location_url",
        ),
    ]
