# Generated by Django 5.2 on 2026-01-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_geometry_latng_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="total_revenue",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("discount", models.PositiveSmallIntegerField()),
                ("quota", models.PositiveIntegerField()),
                ("tickets_bought", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "category_id")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="events.ticketcategory",
            ),
        ),
    ]
