# Generated by Django 5.2 on 2026-01-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="paid_deposit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventplace",
            name="custom_event_deposit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
