# Generated by Django 5.2 on 2026-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_event_paid_deposit_eventplace_custom_event_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="has_quota",
            field=models.BooleanField(default=False),
        ),
    ]
