# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-04-30T20:05:17+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class EventPlaceUpdated(BaseModel):
    event_place_id: int = Field(..., alias="eventPlaceId")
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    min_days: int = Field(..., alias="minDays")


class EventStatusChanged(BaseModel):
    event_id: int = Field(..., alias="eventId")
    status: int


class EventTicketVerified(BaseModel):
    token_id: int = Field(..., alias="tokenId")


class EventUpdated(BaseModel):
    id: int
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    cancel_date: int = Field(..., alias="cancelDate")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")


class NewEventPlaceAvailable(BaseModel):
    event_place_id: int = Field(..., alias="eventPlaceId")
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    min_days: int = Field(..., alias="minDays")


class NewEventRequest(BaseModel):
    id: int
    creator: str
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    cancel_date: int = Field(..., alias="cancelDate")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")


class RoleAdminChanged(BaseModel):
    role: str
    previous_admin_role: str = Field(..., alias="previousAdminRole")
    new_admin_role: str = Field(..., alias="newAdminRole")


class RoleGranted(BaseModel):
    role: str
    account: str
    sender: str


class RoleRevoked(BaseModel):
    role: str
    account: str
    sender: str


class Approval(BaseModel):
    owner: str
    approved: str
    token_id: int = Field(..., alias="tokenId")


class ApprovalForAll(BaseModel):
    owner: str
    operator: str
    approved: bool


class TicketMinted(BaseModel):
    event_id: int = Field(..., alias="eventId")
    ticket_id: int = Field(..., alias="ticketId")
    owner: str
    digest: str
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class TicketRedeemed(BaseModel):
    ticket_id: int = Field(..., alias="ticketId")


class Transfer(BaseModel):
    from_: str = Field(..., alias="from")
    to: str
    token_id: int = Field(..., alias="tokenId")
