# Generated by Django 5.2 on 2025-10-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ktp", models.CharField(blank=True, max_length=16)),
                ("director_id", models.CharField(blank=True, max_length=16)),
                (
                    "akta",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/akta/"
                    ),
                ),
                (
                    "sk_kemenkumham",
                    models.FileField(
                        blank=True, null=True, upload_to="applications/sk/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
