# noqa: N999
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-04T00:03:35+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Approval(BaseModel):
    class Config:
        allow_mutation = False

    owner: str
    approved: str
    token_id: int = Field(..., alias="tokenId")


class ApprovalForAll(BaseModel):
    class Config:
        allow_mutation = False

    owner: str
    operator: str
    approved: bool


class RoleAdminChanged(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    previous_admin_role: str = Field(..., alias="previousAdminRole")
    new_admin_role: str = Field(..., alias="newAdminRole")


class RoleGranted(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    account: str
    sender: str


class RoleRevoked(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    account: str
    sender: str


class TicketMinted(BaseModel):
    class Config:
        allow_mutation = False

    event_id: int = Field(..., alias="eventId")
    ticket_id: int = Field(..., alias="ticketId")
    owner: str
    digest: str
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class TicketRedeemed(BaseModel):
    class Config:
        allow_mutation = False

    ticket_id: int = Field(..., alias="ticketId")


class Transfer(BaseModel):
    class Config:
        allow_mutation = False

    from_: str = Field(..., alias="from")
    to: str
    token_id: int = Field(..., alias="tokenId")


class CyberValleyEvents(BaseModel):
    class Config:
        allow_mutation = False

    approval: Approval | None = Field(None, alias="Approval")
    approval_for_all: ApprovalForAll | None = Field(None, alias="ApprovalForAll")
    role_admin_changed: RoleAdminChanged | None = Field(None, alias="RoleAdminChanged")
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
    ticket_minted: TicketMinted | None = Field(None, alias="TicketMinted")
    ticket_redeemed: TicketRedeemed | None = Field(None, alias="TicketRedeemed")
    transfer: Transfer | None = Field(None, alias="Transfer")
