# noqa: N999
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-04T00:03:35+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class EventPlaceUpdated(BaseModel):
    class Config:
        allow_mutation = False

    event_place_id: int = Field(..., alias="eventPlaceId")
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    min_days: int = Field(..., alias="minDays")


class EventStatusChanged(BaseModel):
    class Config:
        allow_mutation = False

    event_id: int = Field(..., alias="eventId")
    status: int


class EventTicketVerified(BaseModel):
    class Config:
        allow_mutation = False

    token_id: int = Field(..., alias="tokenId")


class EventUpdated(BaseModel):
    class Config:
        allow_mutation = False

    id: int
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    cancel_date: int = Field(..., alias="cancelDate")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")


class NewEventPlaceAvailable(BaseModel):
    class Config:
        allow_mutation = False

    event_place_id: int = Field(..., alias="eventPlaceId")
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    min_days: int = Field(..., alias="minDays")


class NewEventRequest(BaseModel):
    class Config:
        allow_mutation = False

    id: int
    creator: str
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    cancel_date: int = Field(..., alias="cancelDate")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")


class RoleAdminChanged(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    previous_admin_role: str = Field(..., alias="previousAdminRole")
    new_admin_role: str = Field(..., alias="newAdminRole")


class RoleGranted(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    account: str
    sender: str


class RoleRevoked(BaseModel):
    class Config:
        allow_mutation = False

    role: str
    account: str
    sender: str


class CyberValleyEvents(BaseModel):
    class Config:
        allow_mutation = False

    event_place_updated: EventPlaceUpdated | None = Field(
        None, alias="EventPlaceUpdated"
    )
    event_status_changed: EventStatusChanged | None = Field(
        None, alias="EventStatusChanged"
    )
    event_ticket_verified: EventTicketVerified | None = Field(
        None, alias="EventTicketVerified"
    )
    event_updated: EventUpdated | None = Field(None, alias="EventUpdated")
    new_event_place_available: NewEventPlaceAvailable | None = Field(
        None, alias="NewEventPlaceAvailable"
    )
    new_event_request: NewEventRequest | None = Field(None, alias="NewEventRequest")
    role_admin_changed: RoleAdminChanged | None = Field(None, alias="RoleAdminChanged")
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
