# THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY!
#
# Generated by: python manage.py generate_types
# Source: Contract ABIs in ethereum_artifacts/
#
# To modify this file:
#   1. Update the Solidity contract and recompile
#   2. For field-specific patches (validators), edit `FIELD_PATCHES` at
#      `cyber_valley/indexer/management/commands/generate_types.py`
#   3. For custom validators, edit:
#      cyber_valley/indexer/service/events/patches.py
#   4. Then regenerate with: make -C backend gen-types
#
# See: cyber_valley/indexer/service/events/README.md for details
#
# ruff: noqa: N999


from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field

from .patches import validate_digest, validate_role


class EventPlaceUpdated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    provider: str
    event_place_id: int = Field(..., alias="eventPlaceId")
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    days_before_cancel: int = Field(..., alias="daysBeforeCancel")
    min_days: int = Field(..., alias="minDays")
    available: bool
    status: int
    digest: Annotated[str, BeforeValidator(validate_digest)]
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class EventStatusChanged(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    event_id: int = Field(..., alias="eventId")
    status: int


class EventTicketVerified(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    token_id: int = Field(..., alias="tokenId")


class EventUpdated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: int
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")
    digest: Annotated[str, BeforeValidator(validate_digest)]
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class NewEventPlaceRequest(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: int
    requester: str
    max_tickets: int = Field(..., alias="maxTickets")
    min_tickets: int = Field(..., alias="minTickets")
    min_price: int = Field(..., alias="minPrice")
    days_before_cancel: int = Field(..., alias="daysBeforeCancel")
    min_days: int = Field(..., alias="minDays")
    available: bool
    digest: Annotated[str, BeforeValidator(validate_digest)]
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class NewEventRequest(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: int
    creator: str
    event_place_id: int = Field(..., alias="eventPlaceId")
    ticket_price: int = Field(..., alias="ticketPrice")
    start_date: int = Field(..., alias="startDate")
    days_amount: int = Field(..., alias="daysAmount")
    digest: Annotated[str, BeforeValidator(validate_digest)]
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class RoleAdminChanged(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    previous_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="previousAdminRole"
    )
    new_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="newAdminRole"
    )


class RoleGranted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class RoleRevoked(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class CyberValleyEvents(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    event_place_updated: EventPlaceUpdated | None = Field(
        None, alias="EventPlaceUpdated"
    )
    event_status_changed: EventStatusChanged | None = Field(
        None, alias="EventStatusChanged"
    )
    event_ticket_verified: EventTicketVerified | None = Field(
        None, alias="EventTicketVerified"
    )
    event_updated: EventUpdated | None = Field(None, alias="EventUpdated")
    new_event_place_request: NewEventPlaceRequest | None = Field(
        None, alias="NewEventPlaceRequest"
    )
    new_event_request: NewEventRequest | None = Field(None, alias="NewEventRequest")
    role_admin_changed: RoleAdminChanged | None = Field(None, alias="RoleAdminChanged")
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
