# THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY!
#
# Generated by: python manage.py generate_types
# Source: Contract ABIs in ethereum_artifacts/
#
# To modify this file:
#   1. Update the Solidity contract and recompile
#   2. For field-specific patches (validators), edit `FIELD_PATCHES` at
#      `cyber_valley/indexer/management/commands/generate_types.py`
#   3. For custom validators, edit:
#      cyber_valley/indexer/service/events/patches.py
#   4. Then regenerate with: make -C backend gen-types
#
# See: cyber_valley/indexer/service/events/README.md for details
#
# ruff: noqa: N999


from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field

from .patches import validate_digest, validate_role


class Approval(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    owner: str
    approved: str
    token_id: int = Field(..., alias="tokenId")


class ApprovalForAll(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    owner: str
    operator: str
    approved: bool


class RoleAdminChanged(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    previous_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="previousAdminRole"
    )
    new_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="newAdminRole"
    )


class RoleGranted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class RoleRevoked(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class TicketMinted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    event_id: int = Field(..., alias="eventId")
    ticket_id: int = Field(..., alias="ticketId")
    owner: str
    digest: Annotated[str, BeforeValidator(validate_digest)]
    hash_function: int = Field(..., alias="hashFunction")
    size: int


class TicketRedeemed(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    ticket_id: int = Field(..., alias="ticketId")


class Transfer(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    from_: str = Field(..., alias="from")
    to: str
    token_id: int = Field(..., alias="tokenId")


class CyberValleyEvents(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    approval: Approval | None = Field(None, alias="Approval")
    approval_for_all: ApprovalForAll | None = Field(None, alias="ApprovalForAll")
    role_admin_changed: RoleAdminChanged | None = Field(None, alias="RoleAdminChanged")
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
    ticket_minted: TicketMinted | None = Field(None, alias="TicketMinted")
    ticket_redeemed: TicketRedeemed | None = Field(None, alias="TicketRedeemed")
    transfer: Transfer | None = Field(None, alias="Transfer")
