# THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY!
#
# Generated by: python manage.py generate_types
# Source: Contract ABIs in ethereum_artifacts/
#
# To modify this file:
#   1. Update the Solidity contract and recompile
#   2. For field-specific patches (validators), edit `FIELD_PATCHES` at
#      `cyber_valley/indexer/management/commands/generate_types.py`
#   3. For custom validators, edit:
#      cyber_valley/indexer/service/events/patches.py
#   4. Then regenerate with: make -C backend gen-types
#
# See: cyber_valley/indexer/service/events/README.md for details
#
# ruff: noqa: N999


from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field

from .patches import validate_role


class DistributionProfileCreated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    profile_id: int = Field(..., alias="profileId")
    owner: str
    recipients: list[str]
    shares: list[int]


class DistributionProfileUpdated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    profile_id: int = Field(..., alias="profileId")
    recipients: list[str]
    shares: list[int]


class EventProfileSet(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    event_id: int = Field(..., alias="eventId")
    profile_id: int = Field(..., alias="profileId")


class ProfileDeactivated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    profile_id: int = Field(..., alias="profileId")


class ProfileManagerGranted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    account: str
    bps: int


class ProfileOwnershipTransferred(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    profile_id: int = Field(..., alias="profileId")
    previous_owner: str = Field(..., alias="previousOwner")
    new_owner: str = Field(..., alias="newOwner")


class RevenueDistributed(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    amount: int
    event_id: int = Field(..., alias="eventId")


class RoleAdminChanged(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    previous_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="previousAdminRole"
    )
    new_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="newAdminRole"
    )


class RoleGranted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class RoleRevoked(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class CyberValleyEvents(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    distribution_profile_created: DistributionProfileCreated | None = Field(
        None, alias="DistributionProfileCreated"
    )
    distribution_profile_updated: DistributionProfileUpdated | None = Field(
        None, alias="DistributionProfileUpdated"
    )
    event_profile_set: EventProfileSet | None = Field(None, alias="EventProfileSet")
    profile_deactivated: ProfileDeactivated | None = Field(
        None, alias="ProfileDeactivated"
    )
    profile_manager_granted: ProfileManagerGranted | None = Field(
        None, alias="ProfileManagerGranted"
    )
    profile_ownership_transferred: ProfileOwnershipTransferred | None = Field(
        None, alias="ProfileOwnershipTransferred"
    )
    revenue_distributed: RevenueDistributed | None = Field(
        None, alias="RevenueDistributed"
    )
    role_admin_changed: RoleAdminChanged | None = Field(
        None, alias="RoleAdminChanged"
    )
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
