# THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY!
#
# Generated by: python manage.py generate_types
# Source: Contract ABIs in ethereum_artifacts/
#
# To modify this file:
#   1. Update the Solidity contract and recompile
#   2. For field-specific patches (validators), edit `FIELD_PATCHES` at
#      `cyber_valley/indexer/management/commands/generate_types.py`
#   3. For custom validators, edit:
#      cyber_valley/indexer/service/events/patches.py
#   4. Then regenerate with: make -C backend gen-types
#
# See: cyber_valley/indexer/service/events/README.md for details
#
# ruff: noqa: N999


from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field

from .patches import validate_role


class ActiveUpdated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    user: str
    timestamp: int


class ConfigUpdated(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    referral_bonus: int = Field(..., alias="referralBonus")
    seconds_until_inactive: int = Field(..., alias="secondsUntilInactive")
    only_reward_active_referrers: bool = Field(..., alias="onlyRewardActiveReferrers")
    level1: int
    level2: int
    level3: int


class ReferrerSet(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    referee: str
    referrer: str


class RoleAdminChanged(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    previous_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="previousAdminRole"
    )
    new_admin_role: Annotated[str, BeforeValidator(validate_role)] = Field(
        ..., alias="newAdminRole"
    )


class RoleGranted(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class RoleRevoked(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    role: Annotated[str, BeforeValidator(validate_role)]
    account: str
    sender: str


class CyberValleyEvents(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    active_updated: ActiveUpdated | None = Field(None, alias="ActiveUpdated")
    config_updated: ConfigUpdated | None = Field(None, alias="ConfigUpdated")
    referrer_set: ReferrerSet | None = Field(None, alias="ReferrerSet")
    role_admin_changed: RoleAdminChanged | None = Field(None, alias="RoleAdminChanged")
    role_granted: RoleGranted | None = Field(None, alias="RoleGranted")
    role_revoked: RoleRevoked | None = Field(None, alias="RoleRevoked")
