# noqa: N999
# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2025-05-04T00:03:35+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Approval(BaseModel):
    class Config:
        allow_mutation = False

    owner: str
    spender: str
    value: int


class Transfer(BaseModel):
    class Config:
        allow_mutation = False

    from_: str = Field(..., alias="from")
    to: str
    value: int


class CyberValleyEvents(BaseModel):
    class Config:
        allow_mutation = False

    approval: Approval | None = Field(None, alias="Approval")
    eip712_domain_changed: dict[str, Any] | None = Field(
        None, alias="EIP712DomainChanged"
    )
    transfer: Transfer | None = Field(None, alias="Transfer")
