---
domain_name: cvland-tickets.aishift.co
dotenv_src: ../.env.production
dotenv_dest: ".env"
letsencrypt_email: tech@aishift.co
ipfs_data_volume: ipfs-data
ipfs_staging_volume: ipfs-staging
ganache_data_volume: ganache-data
