# Generated by Django 5.2 on 2026-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LastProcessedBlock",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Last Processed Block",
                "verbose_name_plural": "Last Processed Block",
            },
        ),
        migrations.CreateModel(
            name="LogProcessingError",
            fields=[
                ("tx_hash", models.TextField(primary_key=True, serialize=False)),
                ("block_number", models.PositiveIntegerField()),
                ("log_receipt", models.BinaryField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
