# Generated by Django 5.2 on 2025-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogProcessingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_number", models.PositiveIntegerField()),
                ("log_receipt", models.JSONField()),
                ("tx_hash", models.TextField()),
                ("error", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
