# Generated by Django 5.2 on 2025-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexer", "0002_logprocessingerror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logprocessingerror",
            name="log_receipt",
            field=models.TextField(),
        ),
    ]
