# Generated by Django 5.2 on 2025-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexer", "0004_alter_logprocessingerror_log_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logprocessingerror",
            name="id",
        ),
        migrations.AlterField(
            model_name="logprocessingerror",
            name="tx_hash",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
