---
- name: Deploy Cyber Valley Tickets
  hosts: backend
  become: true
  vars_files:
    - vars/common.yml

  tasks:
    - name: Installing podman
      ansible.builtin.package:
        name: "podman"
        state: present
