---
- name: "Deploy frontend"
  hosts: all
  become: true
  become_user: root

  vars:
    frontend_src: "../client"
    frontend_dest: "/var/www/{{ domain_name }}"

  vars_files:
    - vars/common.yml

  tasks:
    - name: "Install packages"
      ansible.builtin.package: "name={{ item }} state=present"
      with_items:
        - rsync

    - name: "Build frontend"
      delegate_to: localhost
      become: false
      environment:
        PUBLIC_API_HOST: "https://{{ domain_name }}"
        PUBLIC_THIRDWEB_PUBLIC_CLIENT_ID: "{{ lookup('env', 'PUBLIC_THIRDWEB_PUBLIC_CLIENT_ID', default=undef()) }}"
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{ frontend_src }}"
      changed_when: true

    - name: "Create dest directory"
      ansible.builtin.file:
        path: "{{ frontend_dest }}"
        state: directory
        mode: "0644"

    - name: "Distribute"
      ansible.posix.synchronize:
        src: "{{ frontend_src }}/dist/"
        dest: "{{ frontend_dest }}"
