---
- name: "Deploy frontend"
  hosts: all
  become: true
  become_user: root

  vars:
    frontend_src: "../client"
    frontend_dest: "/www"

  vars_files:
    - vars/common.yml

  tasks:
    - name: "Install packages"
      ansible.builtin.package: "name={{ item }} state=present"
      with_items:
        - rsync

    - name: "Build frontend"
      delegate_to: localhost
      become: false
      environment:
        VITE_API_HOST: "{{ api_host }}"
        VITE_THIRDWEB_PUBLIC_CLIENT_ID: "{{ lookup(
          'ansible.builtin.env',
          'VITE_THIRDWEB_PUBLIC_CLIENT_ID',
          default=undef()) }}"
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{ frontend_src }}"
      changed_when: true

    - name: "Create dest directory"
      ansible.builtin.file:
        path: /www
        state: directory
        mode: "0644"

    - name: "Deploy"
      block:
        - name: "Copy dotenv"
          ansible.builtin.copy:
            src: "{{ dotenv_src }}"
            dest: "{{ dotenv_dest }}"
            mode: '0600'

        - name: "Distribute"
          ansible.posix.synchronize:
            src: "{{ frontend_src }}/dist"
            dest: "{{ frontend_dest }}"

      always:
        - name: "Remove dotenv"
          ansible.builtin.file:
            path: "{{ dotenv_dest }}"
            state: absent
          when: true
          check_mode: false
