---
- name: "Start podman containers with cron"
  hosts: all
  tasks:
    - name: "Podman restart containers"
      ansible.builtin.cron:
        state: absent
        name: "Podman restart containers"
        minute: "5"
        job: "podman start --filter restart-policy=always --all"
