[project]
name = "ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-core>=2.18.5",
    "ansible-lint>=25.2.1",
    "yamllint>=1.37.0",
]
