---
- name: "Setup Debian"
  hosts: backend
  vars_files:
    - vars/common.yml
  tasks:
    - name: "Install packages"
      become: true
      become_user: root
      ansible.builtin.package:
        update_cache: true
        name:
          - podman
          - slirp4netns 
          - uidmap 

    - name: "Extend bash profile"
      ansible.builtin.blockinfile:
        state: present
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          alias p='podman'
          alias pl="p logs --tail=50"
          alias plf="pl -f"
          df -h
          p ps -a
