# Generated by Django 5.2 on 2025-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shaman_verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="requester_telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="requester_telegram_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
