# Generated by Django 5.2 on 2025-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web3_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=42, primary_key=True, serialize=False),
        ),
    ]
