# Generated by Django 5.2 on 2025-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web3_auth", "0002_alter_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
