# Generated by Django 5.2 on 2025-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cybervalleyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("creator", "Creator"),
                    ("master", "Master"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
