# Generated by Django 5.2 on 2025-05-04 13:03

import cyber_valley.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cybervalleyuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cybervalleyuser',
            name='address',
            field=cyber_valley.users.models.AddressField(max_length=42, primary_key=True, serialize=False),
        ),
    ]
