# Generated by Django 5.2 on 2025-05-06 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_cybervalleyuser_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("discord", "Discord"),
                            ("whatsapp", "Whatsapp"),
                        ]
                    ),
                ),
                ("value", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
