# Generated by Django 5.2 on 2025-05-09 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_usersocials"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersocials",
            unique_together={("user", "network", "value")},
        ),
    ]
