# Generated by Django 5.2 on 2025-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_usersocials_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cybervalleyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("creator", "Creator"),
                    ("localprovider", "Local Provider"),
                    ("master", "Master"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
