# Generated by Django 5.2 on 2025-10-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_cybervalleyuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cybervalleyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("creator", "Creator"),
                    ("localprovider", "Local Provider"),
                    ("verifiedshaman", "Verified Shaman"),
                    ("master", "Master"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
