# Generated by Django 5.2 on 2025-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_verified_shaman_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersocials",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
