# Generated by Django 5.2 on 2026-01-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_usersocials_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="cybervalleyuser",
            name="default_share",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
