# Generated by Django 5.2 on 2026-02-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_cybervalleyuser_default_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                            ("creator", "Creator"),
                            ("localprovider", "Local Provider"),
                            ("verifiedshaman", "Verified Shaman"),
                            ("master", "Master"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "users_role",
            },
        ),
        migrations.AddField(
            model_name="cybervalleyuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.role"
            ),
        ),
    ]
