# Generated by Django 5.2 on 2026-02-01 20:45

from typing import Any

from django.db import migrations


def create_roles_and_migrate(apps: Any, schema_editor: Any) -> None:
    """Create Role objects and migrate existing role data to M2M."""
    Role = apps.get_model("users", "Role")
    CyberValleyUser = apps.get_model("users", "CyberValleyUser")

    # Role choices from Role model
    ROLE_CHOICES = (
        ("customer", "Customer"),
        ("staff", "Staff"),
        ("creator", "Creator"),
        ("localprovider", "Local Provider"),
        ("verifiedshaman", "Verified Shaman"),
        ("master", "Master"),
    )

    # Create Role objects for each role type
    role_map = {}
    for role_value, role_name in ROLE_CHOICES:
        role, _ = Role.objects.get_or_create(name=role_value)
        role_map[role_value] = role

    # Migrate existing single role to M2M roles
    for user in CyberValleyUser.objects.all():
        if user.role and user.role in role_map:
            user.roles.add(role_map[user.role])


def reverse_migration(apps: Any, schema_editor: Any) -> None:
    """Reverse migration - not needed for this case."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_role_cybervalleyuser_roles"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_migrate, reverse_migration),
    ]
